### PR TITLE
Updated to readable-stream@3

### PR DESCRIPTION
**Pull request by mcollina**

### CODE REVIEW

**Comment by gajus** [comment]
Please document in the release notes whats the reason this is a breaking change.

I am assuming you've dropped Node <6 support?

**Comment by mcollina** [comment]
It _is_ documented. Upgraded to readable-stream@3, which is a breaking change on it: https://github.com/nodejs/readable-stream#version-3xx.

**Comment by gajus** [comment]
It is not documented in the split2 module.

* https://github.com/mcollina/split2/releases does not mention it
* There is no https://github.com/mcollina/split2/blob/master/CHANGELOG.md

**Comment by mcollina** [comment]
There is a tagged release, listing the update to readable-stream@3 as the only change: https://github.com/mcollina/split2/releases/tag/v3.0.0.

**Pull request merged**
